### ISSUE TITLE
Seriallization exception when running benchmarks

### ISSUE THREAD

**Issue by svenkeidel** [monto-editor/services-java#2]
```
startup broker: /Users/svenkeidel/Documents/broker/dist/build/broker/broker
startup services: /Users/svenkeidel/services-gradle/services-java/build/libs/services-java.jar
setup connection
ready
warmup [1/2553]: /Users/svenkeidel/Documents/apache-ant-1.9.7/AbstractAccessTask.java
Tear Down
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    monto/service/gson/DiscoveryResponseDeserializer.deserialize(Lcom/google/gson/JsonElement;Ljava/lang/reflect/Type;Lcom/google/gson/JsonDeserializationContext;)Lmonto/service/discovery/DiscoveryResponse; @29: invokestatic
  Reason:
    Type 'monto/service/discovery/ServiceDescription' (current frame, stack[0]) is not assignable to '[Ljava/lang/Object;'
  Current Frame:
    bci: @29
    flags: { }
    locals: { 'monto/service/gson/DiscoveryResponseDeserializer', 'com/google/gson/JsonElement', 'java/lang/reflect/Type', 'com/google/gson/JsonDeserializationContext' }
    stack: { 'monto/service/discovery/ServiceDescription' }
  Bytecode:
    0x0000000: 2bb6 0015 9a00 0dbb 0013 5912 1bb7 001d
    0x0000010: bf2d 2b12 20b9 0022 0300 c000 27b8 0029
    0x0000020: 3a04 bb00 2f59 1904 b700 31b0          
  Stackmap Table:
    same_frame(@17)

    at monto.service.gson.GsonMonto.<clinit>(GsonMonto.java:24)
    at monto.connection.PublishSource.sendMessage(PublishSource.java:19)
    at monto.service.benchmark.ServiceIntegrationBenchmark.measure(ServiceIntegrationBenchmark.java:117)
    at monto.service.benchmark.Benchmark.warmup(Benchmark.java:27)
    at monto.service.benchmark.Benchmark.runBenchmark(Benchmark.java:51)
    at monto.service.benchmark.ServiceIntegrationBenchmark.main(ServiceIntegrationBenchmark.java:131)
```

**Comment by StareInTheAir** [comment]
Please retest with new standalone java-services. Also make sure
- to comment in `srcDir benchmarks` in the `sourceSets` section in `build.gradle` (also now referenced in README.me)
- to run `Gradle` -> `Refresh Gradle Project` from context menu of the `services-java` folder in Package Explorer

after pulling.
