### ISSUE TITLE
ClassNotFound exception during deregistration

### ISSUE THREAD

**Issue by svenkeidel** [monto-editor/services-java#3]
```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: monto/service/registration/DeregisterService
        at monto.service.MontoService.stop(MontoService.java:153)
        at monto.service.java8.JavaServices$1.run(JavaServices.java:39)
Caused by: java.lang.ClassNotFoundException: monto.service.registration.DeregisterService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```

**Comment by svenkeidel** [comment]
@wpmp, sorry, wrong assignee.

**Comment by StareInTheAir** [comment]
Can't reproduce.

You can try to refresh the Eclipse project, run Gradle -> Refresh Gradle Project from context menu of the services-java folder in Package Explorer and rebuild the entire project.

**Comment by svenkeidel** [comment]
Ok, I'll try.

**Comment by svenkeidel** [comment]
Now it works, weird.
